version: '3.8'
services:
  superkassa:
    image: sk
    build: .
    container_name: sk-container
    ports:
      - "8080:8080"
    depends_on:
      - sk_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sk_db:5432/sk_example_db
      - SPRING_DATASOURCE_USERNAME=sk_example_user
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver

  sk_db:
    image: postgres:14-alpine
    container_name: sk_db-container
    ports:
      - "6541:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=sk_example_user
      - POSTGRES_DB=sk_example_db